### ISSUE TITLE
Images to srt

### ISSUE THREAD

**Issue by arcadas** [SjorsO/sup#3]
Hi, thanks for this tool! Could you share, that how do you convert images to srt file by Tesseract?

**Comment by SjorsO** [comment]
OCRing and  building the srt file is out of scope for this package. But basically:
1. Use Tesseract (with [a wrapper](https://github.com/thiagoalessio/tesseract-ocr-for-php)) to convert the images to text
2. Combine the ocr'd text with the timestamps from the sup file
3. Build the srt
